name: TestPipeline

on:
  push:
    branches: [main, master]

jobs:

  build:
  
    runs-on: ubuntu-latest

    strategy:
      matrix: 
        node-version: [14.x]

    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:  
          node-version: ${{ matrix.node-version }}
      - name: Run clean install
        run: npm ci
      - name: Run build
        run: npm run build
      - name: Run linting
        run: npm run lint
      - name: Run export
        run: npm run export

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: out