name: TestPipeline

on:
  push:
    branches: [main, master]

jobs:
  lintTest:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Install depenfencies
        run: npm install
      - name: Run linting
        run: npm run lint
  # deploy:
  #   name: Deployment
  #   runs-on: ubuntu-latest
  #   needs: [lintTest]